// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2018-05-18 18:43:16.0831223 +0800 CST m=+0.006004201
package easyjson

import "encoding/json"

// Object implement JSON

func (v Object) String() string { return v.JSONString() }
func (v Object) JSONString() string {
	bytes, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return string(bytes)
}

// Array implement JSON

func (v Array) String() string { return v.JSONString() }
func (v Array) JSONString() string {
	bytes, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return string(bytes)
}

// String implement JSON

func (v String) String() string { return v.JSONString() }
func (v String) JSONString() string {
	bytes, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return string(bytes)
}

// Boolean implement JSON

func (v Boolean) String() string { return v.JSONString() }
func (v Boolean) JSONString() string {
	bytes, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return string(bytes)
}

// Number implement JSON

func (v Number) String() string { return v.JSONString() }
func (v Number) JSONString() string {
	bytes, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return string(bytes)
}
